#ifndef CONTAINER_CONFIG_H
#define CONTAINER_CONFIG_H

#define CONTAINER_TARGET_TEMP 40.0f

#define CONTAINER_BANG_BANG_DEVIATION 1.0f
#define CONTAINER_BANG_BANG_PERIOD_MS 100

#define CONTAINER_ITERATIONS 1000

#define CONTAINER_BANG_BANG_FINITE_PERIOD_MS 100

#define CONTAINER_PID_PERIOD_MS 100
#define CONTAINER_PID_KP 1.2f
#define CONTAINER_PID_KI 0.08f
#define CONTAINER_PID_KD 0.25f
#define CONTAINER_PID_HEATER_MIN 0.0f
#define CONTAINER_PID_HEATER_MAX 1.0f
#define CONTAINER_PID_INTEGRAL_MIN -20.0f
#define CONTAINER_PID_INTEGRAL_MAX 20.0f
#define CONTAINER_PID_LOG_EVERY 20

#define CONTAINER_PID_FINITE_PERIOD_MS 100

#define CONTAINER_FAULT_DEVIATION 1.0f
#define CONTAINER_FAULT_PERIOD_MS 100
#define CONTAINER_FAULT_PRE_ITERATIONS 10

#define CONTAINER_E2E_PERIOD_MS 10
#define CONTAINER_E2E_STABILIZE_ITERS 500
#define CONTAINER_E2E_HEAT_ITERS 300
#define CONTAINER_E2E_COOL_ITERS 1200
#define CONTAINER_E2E_NUM_STEPS 6

#define CONTAINER_TOGGLE_TARGET_TEMP 40.0f
#define CONTAINER_TOGGLE_DEVIATION 1.0f
#define CONTAINER_TOGGLE_PERIOD_MS 10
#define CONTAINER_TOGGLE_ON_PERIOD_MS 10
#define CONTAINER_TOGGLE_ITERATIONS 5000

#endif
